name: PHPUnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run phpunit inside docker container
      run: docker build --pull -t phpunittest . && docker run phpunittest phpunit tests/*.test.php
